import matplotlib

TracebackException.from_exception(exc, limit, lookup_lines, capture_locals)
